version: "2"
services:
  webserver:
    image: nginx:alpine
    ports:
      - 8669:80
    restart: always
    volumes:
      - ./devscripts/docker-compose/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./devscripts/docker-compose/nginx-security-headers.conf:/etc/nginx/nginx-security-headers.conf:ro
      - ./devscripts/docker-compose/cache-control-headers.conf:/etc/nginx/cache-control-headers.conf:ro
      - ./logs:/var/log/nginx:rw
      - ./platforms/browser/www:/usr/share/nginx/html  # You must run ionic cordova build browser to generate this directory first
