version: "3"
services:
  web:
    image: cyface/cardgame-ionic
    ports:
      - 5678:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
